# Contaminants

## Imports

In [1]:
import pandas as pd
import pprint as pp
import json

# https://www.datacamp.com/tutorial/settingwithcopywarning-pandas
# https://saturncloud.io/blog/how-to-disable-warnings-in-jupyter-notebook/
import warnings

# Not good, but the warnings were annoying me!!
# warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.filterwarnings(action='ignore')

## Load original contaminants dataset

* Measured air pollutants by the air quality measurement stations of the city of Barcelona
* [Dataset](https://opendata-ajuntament.barcelona.cat/data/en/dataset/contaminants-estacions-mesura-qualitat-aire)

In [ ]:
bronze_contaminants_csv_file_path = './../data/bronze/contaminants/contaminants.csv'

In [ ]:
df_bronze_contaminants = pd.read_csv(bronze_contaminants_csv_file_path)

## Original contaminants dataset EDA

In [ ]:
# 21 Rows and 3 Columns
df_bronze_contaminants.shape

(21, 3)

In [ ]:
# Display the first 5 rows of the DataFrame
df_bronze_contaminants.head()

   Codi_Contaminant Desc_Contaminant Unitats
0                 1              SO2   µg/m³
1                 6               CO   mg/m³
2                 7               NO   µg/m³
3                 8              NO2   µg/m³
4                 9            PM2.5   µg/m³

In [ ]:
# Display the last 5 rows of the DataFrame
df_bronze_contaminants.tail()

    Codi_Contaminant                Desc_Contaminant Unitats
16               114                             O3*   µg/m³
17               996   Flow 2 (Mesura interna equip)     NaN
18               997   Flow 1 (Mesura interna equip)     NaN
19               998  Flow C (Mesura interna equip)
20               999           Biomassa Black Carbon       %

In [ ]:
# Display all data
df_bronze_contaminants

    Codi_Contaminant                Desc_Contaminant Unitats
0                  1                             SO2   µg/m³
1                  6                              CO   mg/m³
2                  7                              NO   µg/m³
3                  8                             NO2   µg/m³
4                  9                           PM2.5   µg/m³
5                 10                            PM10   µg/m³
6                 12                             NOx   µg/m³
7                 14                              O3   µg/m³
8                 22                    Black Carbon   µg/m³
9                101                            SO2*   µg/m³
10               106                             CO*   mg/m³
11               107                             NO*   µg/m³
12               108                            NO2*   µg/m³
13               109                          PM2.5*   µg/m³
14               110                           PM10*   µg/m³
15               112                            Nox*   µg/m³
16               114                             O3*   µg/m³
17               996   Flow 2 (Mesura interna equip)     NaN
18               997   Flow 1 (Mesura interna equip)     NaN
19               998  Flow C (Mesura interna equip)
20               999           Biomassa Black Carbon       %

In [ ]:
# Summary of the DataFrame including column names, their data types, 
# and their non-null values count
df_bronze_contaminants.info()

# 'Codi_Contaminant' -> int code -> Contaminant code
# 'Desc_Contaminant' -> object/string (text) -> Contaminant description
# 'Unitats'          -> object/string (text) -> Contaminant units of measurement

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Codi_Contaminant  21 non-null     int64
 1   Desc_Contaminant  21 non-null     object
 2   Unitats           19 non-null     object
dtypes: int64(1), object(2)
memory usage: 636.0+ bytes

## Duplicated data and missing values

In [ ]:
# Missing values for each column
missing_values = df_bronze_contaminants.isnull().sum()
missing_values

# Result: 2 NULL or NaN values in the 'Unitats' column
# Real result (by observation of dataset): 3 NULL or NaN values in the 'Unitats' column
# Rows 17, 18, 19

Codi_Contaminant    0
Desc_Contaminant    0
Unitats             2
dtype: int64

In [ ]:
# Missing values for each column
missing_values = df_bronze_contaminants.isna().sum()
missing_values

# Result: 2 NULL or NaN values in the 'Unitats' column
# Real result (by observation of dataset): 3 NULL or NaN values in the 'Unitats' column
# Rows 17, 18, 19

Codi_Contaminant    0
Desc_Contaminant    0
Unitats             2
dtype: int64

In [ ]:
# Get duplicated rows
duplicates = df_bronze_contaminants.duplicated().sum()
print("Duplicates: ", duplicates)

# No duplicated rows
# In reality we have multiple contaminants with 2 ids 
# (same 'Desc_Contaminant' but with an extra '*' char)

Duplicates:  0

In [ ]:
# Display all data
df_bronze_contaminants

    Codi_Contaminant                Desc_Contaminant Unitats
0                  1                             SO2   µg/m³
1                  6                              CO   mg/m³
2                  7                              NO   µg/m³
3                  8                             NO2   µg/m³
4                  9                           PM2.5   µg/m³
5                 10                            PM10   µg/m³
6                 12                             NOx   µg/m³
7                 14                              O3   µg/m³
8                 22                    Black Carbon   µg/m³
9                101                            SO2*   µg/m³
10               106                             CO*   mg/m³
11               107                             NO*   µg/m³
12               108                            NO2*   µg/m³
13               109                          PM2.5*   µg/m³
14               110                           PM10*   µg/m³
15               112                            Nox*   µg/m³
16               114                             O3*   µg/m³
17               996   Flow 2 (Mesura interna equip)     NaN
18               997   Flow 1 (Mesura interna equip)     NaN
19               998  Flow C (Mesura interna equip)
20               999           Biomassa Black Carbon       %

## Changing columns names

In [ ]:
# Original DataFrame columns names
print(list(df_bronze_contaminants.columns))

['Codi_Contaminant', 'Desc_Contaminant', 'Unitats']

In [ ]:
# New DataFrame columns names
new_df_columns_names = ['code', 'description', 'unit']

# Change columns of DataFrame
df_bronze_contaminants.columns = new_df_columns_names

In [ ]:
# Display all data
df_bronze_contaminants

    code                     description   unit
0      1                             SO2  µg/m³
1      6                              CO  mg/m³
2      7                              NO  µg/m³
3      8                             NO2  µg/m³
4      9                           PM2.5  µg/m³
5     10                            PM10  µg/m³
6     12                             NOx  µg/m³
7     14                              O3  µg/m³
8     22                    Black Carbon  µg/m³
9    101                            SO2*  µg/m³
10   106                             CO*  mg/m³
11   107                             NO*  µg/m³
12   108                            NO2*  µg/m³
13   109                          PM2.5*  µg/m³
14   110                           PM10*  µg/m³
15   112                            Nox*  µg/m³
16   114                             O3*  µg/m³
17   996   Flow 2 (Mesura interna equip)    NaN
18   997   Flow 1 (Mesura interna equip)    NaN
19   998  Flow C (Mesura interna equip)
20   999           Biomassa Black Carbon      %

## Remove contaminants

In [ ]:
# Remove contaminants that "don't matter" for the project
contaminants_to_remove_from_df = [22, 996, 997, 998, 999]

# df_bronze_contaminants is now the old df_bronze_contaminants minus the contaminants
# which the code are in the 'contaminants_to_remove_from_df' list
df_bronze_contaminants = df_bronze_contaminants[
    ~df_bronze_contaminants.code.isin(contaminants_to_remove_from_df)
]

# Display all data
df_bronze_contaminants

    code description   unit
0      1         SO2  µg/m³
1      6          CO  mg/m³
2      7          NO  µg/m³
3      8         NO2  µg/m³
4      9       PM2.5  µg/m³
5     10        PM10  µg/m³
6     12         NOx  µg/m³
7     14          O3  µg/m³
9    101        SO2*  µg/m³
10   106         CO*  mg/m³
11   107         NO*  µg/m³
12   108        NO2*  µg/m³
13   109      PM2.5*  µg/m³
14   110       PM10*  µg/m³
15   112        Nox*  µg/m³
16   114         O3*  µg/m³

## EDA conclusions

- All contaminants have the __same unit (with the exception of the contaminant 'CO' / 'CO*' using mg/m³)__.
    - __All others__ are measured in __µg/m³__.
- There is a relationship between the __previous contaminant code__ and the __new contaminant code (plus 100)__.
- There is a relationship between the __previous contaminant description__ and the __new contaminant description (added '*' char)__.
- There are 16 entries (contaminants). But since they are 'duplicated', __there are only 8 "valid" contaminants__.

- __We will only study/forecast only the 3 most important to the city of barcelona__.

In [ ]:
df_key_contaminants: pd.DataFrame = df_bronze_contaminants.copy()

## Standardizing text columns

In [19]:
df_key_contaminants.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16 entries, 0 to 16
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   code         16 non-null     int64
 1   description  16 non-null     object
 2   unit         16 non-null     object
dtypes: int64(1), object(2)
memory usage: 512.0+ bytes

In [20]:
# Standardizing text data

df_key_contaminants.unit = df_key_contaminants.unit.str.strip()
# df_key_contaminants.unit = df_key_contaminants.unit.astype(str)

df_key_contaminants.description = \
    df_key_contaminants.description\
    .str.strip()\
    .str.upper()

# df_key_contaminants.description = df_key_contaminants.description.astype(str)

In [ ]:
# Display all data
df_key_contaminants

    code description   unit
0      1         SO2  µg/m³
1      6          CO  mg/m³
2      7          NO  µg/m³
3      8         NO2  µg/m³
4      9       PM2.5  µg/m³
5     10        PM10  µg/m³
6     12         NOX  µg/m³
7     14          O3  µg/m³
9    101        SO2*  µg/m³
10   106         CO*  mg/m³
11   107         NO*  µg/m³
12   108        NO2*  µg/m³
13   109      PM2.5*  µg/m³
14   110       PM10*  µg/m³
15   112        NOX*  µg/m³
16   114         O3*  µg/m³

In [ ]:
# Remove '*' from the new contaminants description
df_key_contaminants.description = df_key_contaminants.description.str.replace('*', '')

# Replace 'NOX' for 'NOx'
df_key_contaminants.description = df_key_contaminants.description.str.replace('X', 'x')

# Possible problem with data onward (description name can be used as variable names,
# keys or column names)
# PM2.5 -> The '.' can be a problem and will be replaced with '_'
df_key_contaminants.description = df_key_contaminants.description.str.replace('.', '_')

# Show all data
df_key_contaminants

    code description   unit
0      1         SO2  µg/m³
1      6          CO  mg/m³
2      7          NO  µg/m³
3      8         NO2  µg/m³
4      9       PM2_5  µg/m³
5     10        PM10  µg/m³
6     12         NOx  µg/m³
7     14          O3  µg/m³
9    101         SO2  µg/m³
10   106          CO  mg/m³
11   107          NO  µg/m³
12   108         NO2  µg/m³
13   109       PM2_5  µg/m³
14   110        PM10  µg/m³
15   112         NOx  µg/m³
16   114          O3  µg/m³

## Save data to csv file

In [ ]:
silver_contaminants_csv_file_path = './../data/silver/contaminants/contaminants.csv'

In [ ]:
df_silver_contaminants = df_key_contaminants.copy()
df_silver_contaminants.to_csv(silver_contaminants_csv_file_path, index=False)

In [ ]:
df_test_silver_read_csv = pd.read_csv(silver_contaminants_csv_file_path)
df_test_silver_read_csv

    code description   unit
0      1         SO2  µg/m³
1      6          CO  mg/m³
2      7          NO  µg/m³
3      8         NO2  µg/m³
4      9       PM2_5  µg/m³
5     10        PM10  µg/m³
6     12         NOx  µg/m³
7     14          O3  µg/m³
8    101         SO2  µg/m³
9    106          CO  mg/m³
10   107          NO  µg/m³
11   108         NO2  µg/m³
12   109       PM2_5  µg/m³
13   110        PM10  µg/m³
14   112         NOx  µg/m³
15   114          O3  µg/m³

## Create and test code to implement ContaminantManager class

In [ ]:
# Shortning variable name
df = df_silver_contaminants

In [29]:
# Each contaminant has 2 codes
df['description'].value_counts()

description
SO2      2
CO       2
NO       2
NO2      2
PM2_5    2
PM10     2
NOx      2
O3       2
Name: count, dtype: int64

In [31]:
# Get distinct contaminant descriptions
distinct_contaminant_descriptions = set(df.description)

# Dictionary to hold contaminant data without duplications
# and with the multiple contaminants codes in a list 
contaminants_data_dict = {}

In [32]:
for description in distinct_contaminant_descriptions:
    
    # Creates a DataFrame with 2 rows (each contaminants have two codes -> two rows)
    df_unique_contaminant = df[df.description == description]
    
    # Iterate the DataFrame rows
    for index, row in df_unique_contaminant.iterrows():
        
        # Is already a key in the dictionary? No, then is added to it
        if row.description not in contaminants_data_dict:
            
            contaminants_data_dict[row.description] = {}
            contaminants_data_dict[row.description]['unit'] = row.unit
            contaminants_data_dict[row.description]['codes'] = list()
        
        # Add the code to the list of codes
        contaminants_data_dict[row.description]['codes'].append(row.code)

In [33]:
contaminants_data_dict

{'NOx': {'unit': 'µg/m³', 'codes': [12, 112]},
 'O3': {'unit': 'µg/m³', 'codes': [14, 114]},
 'NO2': {'unit': 'µg/m³', 'codes': [8, 108]},
 'NO': {'unit': 'µg/m³', 'codes': [7, 107]},
 'PM2_5': {'unit': 'µg/m³', 'codes': [9, 109]},
 'SO2': {'unit': 'µg/m³', 'codes': [1, 101]},
 'CO': {'unit': 'mg/m³', 'codes': [6, 106]},
 'PM10': {'unit': 'µg/m³', 'codes': [10, 110]}}

In [34]:
contaminants_data_dict['PM10']

{'unit': 'µg/m³', 'codes': [10, 110]}

In [35]:
contaminants_data_dict['CO']

{'unit': 'mg/m³', 'codes': [6, 106]}

In [36]:
contaminants_data_dict['PM2_5']

{'unit': 'µg/m³', 'codes': [9, 109]}

## Save contaminants in JSON format

* [Geeksforgeeks > JSON dump vs JSON dumps](https://www.geeksforgeeks.org/python/python-difference-between-json-dump-and-json-dumps/)
* [DataCamp > JSON tutorial](https://www.datacamp.com/tutorial/json-data-python)

In [37]:
contaminants_json_file_path = './../data/gold/contaminants/contaminants.json'

In [38]:
with open(contaminants_json_file_path, 'w') as json_file:
    json.dump(contaminants_data_dict, json_file)

In [39]:
json_data_test_read = {}

with open(contaminants_json_file_path) as json_file:
    json_data_test_read = json.load(json_file)

In [40]:
json_data_test_read

{'NOx': {'unit': 'µg/m³', 'codes': [12, 112]},
 'O3': {'unit': 'µg/m³', 'codes': [14, 114]},
 'NO2': {'unit': 'µg/m³', 'codes': [8, 108]},
 'NO': {'unit': 'µg/m³', 'codes': [7, 107]},
 'PM2_5': {'unit': 'µg/m³', 'codes': [9, 109]},
 'SO2': {'unit': 'µg/m³', 'codes': [1, 101]},
 'CO': {'unit': 'mg/m³', 'codes': [6, 106]},
 'PM10': {'unit': 'µg/m³', 'codes': [10, 110]}}

## Test ContaminantManagerJSON class

* [Geeksforgeeks import modules from dir](https://www.geeksforgeeks.org/python/python-import-module-from-different-directory/)

In [ ]:
import sys

# Adding code/generic_code to the system path
sys.path.insert(0, './generic_code')

In [ ]:
from ContaminantManagerJSON import ContaminantManagerJSON

In [ ]:
c_manager_obj = ContaminantManagerJSON(contaminants_json_file_path)

In [ ]:
print("Get all contaminants [ContaminantManagerJSON class]")
pp.pprint(c_manager_obj.get_all_contaminants())

Get all contaminants [ContaminantManagerJSON class]
{'CO': {'codes': [6, 106], 'unit': 'mg/m³'},
 'NO': {'codes': [7, 107], 'unit': 'µg/m³'},
 'NO2': {'codes': [8, 108], 'unit': 'µg/m³'},
 'NOx': {'codes': [12, 112], 'unit': 'µg/m³'},
 'O3': {'codes': [14, 114], 'unit': 'µg/m³'},
 'PM10': {'codes': [10, 110], 'unit': 'µg/m³'},
 'PM2_5': {'codes': [9, 109], 'unit': 'µg/m³'},
 'SO2': {'codes': [1, 101], 'unit': 'µg/m³'}}

In [ ]:
print("Get contaminant data by code [ContaminantManagerJSON class]\n")

template = "'{0}' data => '{1}'"
print(template.format("PM10", c_manager_obj.get_contaminant_data_by_code("PM10")))
print(template.format("PM2_5", c_manager_obj.get_contaminant_data_by_code("PM2_5")))
print(template.format("SO2", c_manager_obj.get_contaminant_data_by_code("SO2")))
print(template.format("CO", c_manager_obj.get_contaminant_data_by_code("CO")))

Get contaminant data by code [ContaminantManagerJSON class]
'PM10' data => '{'unit': 'µg/m³', 'codes': [10, 110], 'description': 'PM10'}'
'PM2_5' data => '{'unit': 'µg/m³', 'codes': [9, 109], 'description': 'PM2_5'}'
'SO2' data => '{'unit': 'µg/m³', 'codes': [1, 101], 'description': 'SO2'}'
'CO' data => '{'unit': 'mg/m³', 'codes': [6, 106], 'description': 'CO'}'
'PM10' data -> {'unit': 'µg/m³', 'codes': [10, 110], 'description': 'PM10'}
'PM2_5' data -> {'unit': 'µg/m³', 'codes': [9, 109], 'description': 'PM2_5'}
'SO2' data -> {'unit': 'µg/m³', 'codes': [1, 101], 'description': 'SO2'}
'CO' data -> {'unit': 'mg/m³', 'codes': [6, 106], 'description': 'CO'}

In [ ]:
print("Get contaminant units by code [ContaminantManagerJSON class]\n")

template = "'{0}' units => '{1}'"
print(template.format("PM10", c_manager_obj.get_units_by_code("PM10")))
print(template.format("PM2_5", c_manager_obj.get_units_by_code("PM2_5")))
print(template.format("SO2", c_manager_obj.get_units_by_code("SO2")))
print(template.format("CO", c_manager_obj.get_units_by_code("CO")))

Get contaminant units by code [ContaminantManagerJSON class]

'PM10' units => 'µg/m³'
'PM2_5' units => 'µg/m³'
'SO2' units => 'µg/m³'
'CO' units => 'mg/m³'

In [ ]:
print("Get contaminant description by code [ContaminantManagerJSON class]\n")

template = "Code '{0}' ('{1}') => '{2}'"

print(template.format("10", "PM10", c_manager_obj.get_description_by_code(10)))
print(template.format("110", "PM10", c_manager_obj.get_description_by_code(110)))

print(template.format("9", "PM2_5", c_manager_obj.get_description_by_code(9)))
print(template.format("109", "PM2_5", c_manager_obj.get_description_by_code(109)))

print(template.format("1", "SO2", c_manager_obj.get_description_by_code(1)))
print(template.format("101", "SO2", c_manager_obj.get_description_by_code(101)))

print(template.format("6", "CO", c_manager_obj.get_description_by_code(6)))
print(template.format("106", "CO", c_manager_obj.get_description_by_code(106)))

Get contaminant description by code [ContaminantManagerJSON class]

Code '10' ('PM10') => 'PM10'
Code '110' ('PM10') => 'PM10'
Code '9' ('PM2_5') => 'PM2_5'
Code '109' ('PM2_5') => 'PM2_5'
Code '1' ('SO2') => 'SO2'
Code '101' ('SO2') => 'SO2'
Code '6' ('CO') => 'CO'
Code '106' ('CO') => 'CO'

In [ ]:
# Acabar comentários de JSOJ c_manager
# Refazer c_manager original (tem duplicados e tem de ser transformado internamente em dict)
# Acabar listagem de ficheiros de data

In [ ]:
import contaminants as c_manager

In [ ]:
c_manager_obj = c_manager.ContaminantManager(original_contaminants_path)

In [ ]:
c_manager_obj.DEFAULT_COLUMNS

['code', 'description', 'units']

In [ ]:
c_manager_obj.get_column_names()

['code', 'description', 'units']

In [ ]:
c_manager_obj.get_all_contaminants()

    code                     description  units
0      1                             SO2  µg/m³
1      6                              CO  mg/m³
2      7                              NO  µg/m³
3      8                             NO2  µg/m³
4      9                           PM2.5  µg/m³
5     10                            PM10  µg/m³
6     12                             NOx  µg/m³
7     14                              O3  µg/m³
8     22                    Black Carbon  µg/m³
9    101                            SO2*  µg/m³
10   106                             CO*  mg/m³
11   107                             NO*  µg/m³
12   108                            NO2*  µg/m³
13   109                          PM2.5*  µg/m³
14   110                           PM10*  µg/m³
15   112                            Nox*  µg/m³
16   114                             O3*  µg/m³
17   996   Flow 2 (Mesura interna equip)    NaN
18   997   Flow 1 (Mesura interna equip)    NaN
19   998  Flow C (Mesura interna equip)
20   999           Biomassa Black Carbon      %

In [ ]:
[c_manager_obj.get_description_by_code(1),
c_manager_obj.get_description_by_code(101)]

['SO2', 'SO2*']

In [ ]:
[c_manager_obj.get_units_by_code(1),
c_manager_obj.get_units_by_code(101)]

['µg/m³', 'µg/m³']

In [ ]:
[c_manager_obj.get_contaminant_data_by_code(1),
c_manager_obj.get_contaminant_data_by_code(101)]

[{'code': 1, 'description': 'SO2', 'units': 'µg/m³'},
 {'code': 101, 'description': 'SO2*', 'units': 'µg/m³'}]