# Stations analysis by year

## Import packages

In [1]:
import os
import numpy as np
import pandas as pd

import station as stn
import folium

## List stations changes

In [2]:
csv_files = os.listdir(stn.STATIONS_BASE_PATH)

In [3]:
csv_files

['2018.csv', '2019.csv', '2021.csv', '2022.csv']

## Import data

In [4]:
df_2018 = pd.read_csv(stn.STATIONS_BASE_PATH + '/2018.csv')

eda_cols, df_2019 = stn.load_station_data(
    stn.STATIONS_BASE_PATH + '/2019.csv', 
    stn.station_cols)

_, df_2021 = stn.load_station_data(
    stn.STATIONS_BASE_PATH + '/2021.csv', 
    stn.station_cols)

_, df_2022 = stn.load_station_data(
    stn.STATIONS_BASE_PATH + '/2022.csv', 
    stn.station_cols)

## Stations in the year 2018

In [5]:
# NO2 seems to be the most important contaminant
# followed by O3 and PM10.

# class_1 = Urban or Suburban (city location)
# class_2 = Emission sources 

cols_2018 = ['station_name', 'code_dtes', 'zqa', 'code_eoi', 'longitude',
       'latitude', 'location', 'district_code', 'district_name', 
       'neighborhood_code', 'neighborhood_name', 'class_1', 'class_2',  
       'contaminant_1', 'contaminant_2', 'contaminant_3']

df_2018.columns = cols_2018

df_2018

,station_name,code_dtes,zqa,code_eoi,longitude,latitude,location,district_code,district_name,neighborhood_code,neighborhood_name,class_1,class_2,contaminant_1,contaminant_2,contaminant_3
0,Barcelona - Ciutadella,IL,1,8019050,2.1874,41.3864,Parc de la Ciutadella,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Urbana,Fons,NO2,O3,NaN
1,Barcelona - Eixample,IH,1,8019043,2.1538,41.3853,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,NO2,O3,PM10
2,Barcelona - Gràcia,IJ,1,8019044,2.1534,41.3987,Plaça Gal·la Placídia (Via Augusta - Travesser...,6,Gracia,31,la Vila de Gracia,Urbana,Trànsit,NO2,O3,PM10
3,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.3875,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,NO2,O3,PM10
4,Barcelona - Poblenou,I2,1,8019004,2.2045,41.4039,Plaça Josep Trueta (Pujades - Lope de Vega),10,Sant Marti,68,el Poblenou,Urbana,Fons,NO2,NaN,PM10
5,Barcelona - Sants,ID,1,8019042,2.1331,41.3788,Jardins de Can Mantega (Joan Güell - Violant d...,3,Sants-Montjuic,18,Sants,Urbana,Fons,NO2,NaN,NaN
6,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.4261,Parc de la Vall d’Hebron - c/ Martí Codolar - ...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,NO2,O3,PM10

In [6]:
# 7 stations and 16 columns
df_2018.shape

(7, 16)

In [7]:
stn.print_categorical_cols(df_2018, df_2018.columns)

Column: 'station_name'

Data = ['Barcelona - Ciutadella', 'Barcelona - Eixample', 'Barcelona - Gràcia', 'Barcelona - Palau Reial', 'Barcelona - Poblenou', 'Barcelona - Sants', 'Barcelona - Vall Hebron']
Length = 7

station_name
Barcelona - Ciutadella     1
Barcelona - Eixample       1
Barcelona - Gràcia         1
Barcelona - Palau Reial    1
Barcelona - Poblenou       1
Barcelona - Sants          1
Barcelona - Vall Hebron    1
Name: count, dtype: int64


============================================================
Column: 'code_dtes'

Data = ['IL', 'IH', 'IJ', 'IZ', 'I2', 'ID', 'IN']
Length = 7

code_dtes
IL    1
IH    1
IJ    1
IZ    1
I2    1
ID    1
IN    1
Name: count, dtype: int64


============================================================
Column: 'zqa'

Data = [1]
Length = 1

zqa
1    7
Name: count, dtype: int64


============================================================
Column: 'code_eoi'

Data = [8019050, 8019043, 8019044, 8019057, 8019004, 8019042, 8019054]
Length = 7

code_eoi
8019050    1
8019043    1
8019044    1
8019057    1
8019004    1
8019042    1
8019054    1
Name: count, dtype: int64


============================================================
Column: 'longitude'

Data = [2.1874, 2.1538, 2.1534, 2.1151, 2.2045, 2.1331, 2.148]
Length = 7

longitude
2.1874    1
2.1538    1
2.1534    1
2.1151    1
2.2045    1
2.1331    1
2.1480    1
Name: count, dtype: int64


============================================================
Column: 'latitude'

Data = [41.3864, 41.3853, 41.3987, 41.3875, 41.4039, 41.3788, 41.4261]
Length = 7

latitude
41.3864    1
41.3853    1
41.3987    1
41.3875    1
41.4039    1
41.3788    1
41.4261    1
Name: count, dtype: int64


============================================================
Column: 'location'

Data = ['Parc de la Ciutadella', 'Av. Roma - c/ Comte Urgell', 'Plaça Gal·la Placídia (Via Augusta - Travessera de Gràcia)', 'c/ John Maynard Keynes - c/ de Jordi Girona', 'Plaça Josep Trueta (Pujades - Lope de Vega)', 'Jardins de Can Mantega (Joan Güell - Violant d’Hongria)', 'Parc de la Vall d’Hebron - c/ Martí Codolar - c/ Granja Vella']
Length = 7

location
Parc de la Ciutadella                                            1
Av. Roma - c/ Comte Urgell                                       1
Plaça Gal·la Placídia (Via Augusta - Travessera de Gràcia)       1
c/ John Maynard Keynes - c/ de Jordi Girona                      1
Plaça Josep Trueta (Pujades - Lope de Vega)                      1
Jardins de Can Mantega (Joan Güell - Violant d’Hongria)          1
Parc de la Vall d’Hebron - c/ Martí Codolar - c/ Granja Vella    1
Name: count, dtype: int64


============================================================
Column: 'district_code'

Data = [1, 5, 6, 4, 10, 3, 7]
Length = 7

district_code
1     1
5     1
6     1
4     1
10    1
3     1
7     1
Name: count, dtype: int64


============================================================
Column: 'district_name'

Data = ['Ciutat Vella', 'Eixample', 'Gracia', 'Les Corts', 'Sant Marti', 'Sants-Montjuic', 'Horta-Guinardo']
Length = 7

district_name
Ciutat Vella      1
Eixample          1
Gracia            1
Les Corts         1
Sant Marti        1
Sants-Montjuic    1
Horta-Guinardo    1
Name: count, dtype: int64


============================================================
Column: 'neighborhood_code'

Data = [4, 9, 31, 21, 68, 18, 41]
Length = 7

neighborhood_code
4     1
9     1
31    1
21    1
68    1
18    1
41    1
Name: count, dtype: int64


============================================================
Column: 'neighborhood_name'

Data = ['Sant Pere, Santa Caterina i la Ribera', "la Nova Esquerra de l'Eixample", 'la Vila de Gracia', 'Pedralbes', 'el Poblenou', 'Sants', "la Vall d'Hebron"]
Length = 7

neighborhood_name
Sant Pere, Santa Caterina i la Ribera    1
la Nova Esquerra de l'Eixample           1
la Vila de Gracia                        1
Pedralbes                                1
el Poblenou                              1
Sants                                    1
la Vall d'Hebron                         1
Name: count, dtype: int64


============================================================
Column: 'class_1'

Data = ['Urbana']
Length = 1

class_1
Urbana    7
Name: count, dtype: int64


============================================================
Column: 'class_2'

Data = ['Fons', 'Trànsit']
Length = 2

class_2
Fons       5
Trànsit    2
Name: count, dtype: int64


============================================================
Column: 'contaminant_1'

Data = ['NO2']
Length = 1

contaminant_1
NO2    7
Name: count, dtype: int64


============================================================
Column: 'contaminant_2'

Data = ['O3', nan]
Length = 2

contaminant_2
O3    5
Name: count, dtype: int64


============================================================
Column: 'contaminant_3'

Data = [nan, 'PM10']
Length = 2

contaminant_3
PM10    5
Name: count, dtype: int64


============================================================

## Stations in the year 2019

In [8]:
df_2019

,station,station_name,code_dtes,zqa,code_eoi,longitude,latitude,location,district_code,district_name,neighborhood_code,neighborhood_name,class_1,class_2,contaminant_code
0,50,Barcelona - Ciutadella,IL,1,8019050,2.1874,41.3864,Parc de la Ciutadella,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Urbana,Fons,8
1,50,Barcelona - Ciutadella,IL,1,8019050,2.1874,41.3864,Parc de la Ciutadella,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Urbana,Fons,14
2,50,Barcelona - Ciutadella,IL,1,8019050,2.1874,41.3864,Parc de la Ciutadella,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Urbana,Fons,7
3,50,Barcelona - Ciutadella,IL,1,8019050,2.1874,41.3864,Parc de la Ciutadella,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Urbana,Fons,12
4,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.3853,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,8
5,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.3853,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,14
6,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.3853,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,10
7,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.3853,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,1
8,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.3853,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,6
9,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.3853,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,7
10,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.3853,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,12
11,44,Barcelona - Gràcia,IJ,1,8019044,2.1534,41.3987,Plaça Gal·la Placídia (Via Augusta - Travesser...,6,Gracia,31,la Vila de Gracia,Urbana,Trànsit,8
12,44,Barcelona - Gràcia,IJ,1,8019044,2.1534,41.3987,Plaça Gal·la Placídia (Via Augusta - Travesser...,6,Gracia,31,la Vila de Gracia,Urbana,Trànsit,14
13,44,Barcelona - Gràcia,IJ,1,8019044,2.1534,41.3987,Plaça Gal·la Placídia (Via Augusta - Travesser...,6,Gracia,31,la Vila de Gracia,Urbana,Trànsit,10
14,44,Barcelona - Gràcia,IJ,1,8019044,2.1534,41.3987,Plaça Gal·la Placídia (Via Augusta - Travesser...,6,Gracia,31,la Vila de Gracia,Urbana,Trànsit,1
15,44,Barcelona - Gràcia,IJ,1,8019044,2.1534,41.3987,Plaça Gal·la Placídia (Via Augusta - Travesser...,6,Gracia,31,la Vila de Gracia,Urbana,Trànsit,6
16,44,Barcelona - Gràcia,IJ,1,8019044,2.1534,41.3987,Plaça Gal·la Placídia (Via Augusta - Travesser...,6,Gracia,31,la Vila de Gracia,Urbana,Trànsit,7
17,44,Barcelona - Gràcia,IJ,1,8019044,2.1534,41.3987,Plaça Gal·la Placídia (Via Augusta - Travesser...,6,Gracia,31,la Vila de Gracia,Urbana,Trànsit,12
18,57,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.3875,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,8
19,57,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.3875,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,14
20,57,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.3875,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,10
21,57,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.3875,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,1
22,57,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.3875,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,6
23,57,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.3875,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,7
24,57,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.3875,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,12
25,4,Barcelona - Poblenou,I2,1,8019004,2.2045,41.4039,Plaça Josep Trueta (Pujades - Lope de Vega),10,Sant Marti,68,el Poblenou,Urbana,Fons,8
26,4,Barcelona - Poblenou,I2,1,8019004,2.2045,41.4039,Plaça Josep Trueta (Pujades - Lope de Vega),10,Sant Marti,68,el Poblenou,Urbana,Fons,10
27,4,Barcelona - Poblenou,I2,1,8019004,2.2045,41.4039,Plaça Josep Trueta (Pujades - Lope de Vega),10,Sant Marti,68,el Poblenou,Urbana,Fons,7
28,4,Barcelona - Poblenou,I2,1,8019004,2.2045,41.4039,Plaça Josep Trueta (Pujades - Lope de Vega),10,Sant Marti,68,el Poblenou,Urbana,Fons,12
29,42,Barcelona - Sants,ID,1,8019042,2.1331,41.3788,Jardins de Can Mantega (Joan Güell - Violant d...,3,Sants-Montjuic,18,Sants,Urbana,Fons,8
30,42,Barcelona - Sants,ID,1,8019042,2.1331,41.3788,Jardins de Can Mantega (Joan Güell - Violant d...,3,Sants-Montjuic,18,Sants,Urbana,Fons,7
31,42,Barcelona - Sants,ID,1,8019042,2.1331,41.3788,Jardins de Can Mantega (Joan Güell - Violant d...,3,Sants-Montjuic,18,Sants,Urbana,Fons,12
32,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.4261,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,8
33,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.4261,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,14
34,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.4261,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,10
35,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.4261,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,1
36,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.4261,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,6
37,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.4261,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,12
38,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.4261,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,7

In [9]:
df_2019.shape

(39, 15)

In [10]:
stn.print_categorical_cols(df_2019, eda_cols)

Column: 'station'

Data = [50, 43, 44, 57, 4, 42, 54]
Length = 7

station
43    7
44    7
57    7
54    7
50    4
4     4
42    3
Name: count, dtype: int64


============================================================
Column: 'station_name'

Data = ['Barcelona - Ciutadella', 'Barcelona - Eixample', 'Barcelona - Gràcia', 'Barcelona - Palau Reial', 'Barcelona - Poblenou', 'Barcelona - Sants', 'Barcelona - Vall Hebron']
Length = 7

station_name
Barcelona - Eixample       7
Barcelona - Gràcia         7
Barcelona - Palau Reial    7
Barcelona - Vall Hebron    7
Barcelona - Ciutadella     4
Barcelona - Poblenou       4
Barcelona - Sants          3
Name: count, dtype: int64


============================================================
Column: 'code_dtes'

Data = ['IL', 'IH', 'IJ', 'IZ', 'I2', 'ID', 'IN']
Length = 7

code_dtes
IH    7
IJ    7
IZ    7
IN    7
IL    4
I2    4
ID    3
Name: count, dtype: int64


============================================================
Column: 'zqa'

Data = [1]
Length = 1

zqa
1    39
Name: count, dtype: int64


============================================================
Column: 'code_eoi'

Data = [8019050, 8019043, 8019044, 8019057, 8019004, 8019042, 8019054]
Length = 7

code_eoi
8019043    7
8019044    7
8019057    7
8019054    7
8019050    4
8019004    4
8019042    3
Name: count, dtype: int64


============================================================
Column: 'location'

Data = ['Parc de la Ciutadella', 'Av. Roma - c/ Comte Urgell', 'Plaça Gal·la Placídia (Via Augusta - Travessera de Gràcia)', 'c/ John Maynard Keynes - c/ de Jordi Girona', 'Plaça Josep Trueta (Pujades - Lope de Vega)', 'Jardins de Can Mantega (Joan Güell - Violant d’Hongria)', 'Parc de la Vall d’Hebron. c/ Martí Codolar - c/ Granja Vella']
Length = 7

location
Av. Roma - c/ Comte Urgell                                      7
Plaça Gal·la Placídia (Via Augusta - Travessera de Gràcia)      7
c/ John Maynard Keynes - c/ de Jordi Girona                     7
Parc de la Vall d’Hebron. c/ Martí Codolar - c/ Granja Vella    7
Parc de la Ciutadella                                           4
Plaça Josep Trueta (Pujades - Lope de Vega)                     4
Jardins de Can Mantega (Joan Güell - Violant d’Hongria)         3
Name: count, dtype: int64


============================================================
Column: 'district_code'

Data = [1, 5, 6, 4, 10, 3, 7]
Length = 7

district_code
5     7
6     7
4     7
7     7
1     4
10    4
3     3
Name: count, dtype: int64


============================================================
Column: 'district_name'

Data = ['Ciutat Vella', 'Eixample', 'Gracia', 'Les Corts', 'Sant Marti', 'Sants-Montjuic', 'Horta-Guinardo']
Length = 7

district_name
Eixample          7
Gracia            7
Les Corts         7
Horta-Guinardo    7
Ciutat Vella      4
Sant Marti        4
Sants-Montjuic    3
Name: count, dtype: int64


============================================================
Column: 'neighborhood_code'

Data = [4, 9, 31, 21, 68, 18, 41]
Length = 7

neighborhood_code
9     7
31    7
21    7
41    7
4     4
68    4
18    3
Name: count, dtype: int64


============================================================
Column: 'neighborhood_name'

Data = ['Sant Pere, Santa Caterina i la Ribera', "la Nova Esquerra de l'Eixample", 'la Vila de Gracia', 'Pedralbes', 'el Poblenou', 'Sants', "la Vall d'Hebron"]
Length = 7

neighborhood_name
la Nova Esquerra de l'Eixample           7
la Vila de Gracia                        7
Pedralbes                                7
la Vall d'Hebron                         7
Sant Pere, Santa Caterina i la Ribera    4
el Poblenou                              4
Sants                                    3
Name: count, dtype: int64


============================================================
Column: 'class_1'

Data = ['Urbana']
Length = 1

class_1
Urbana    39
Name: count, dtype: int64


============================================================
Column: 'class_2'

Data = ['Fons', 'Trànsit']
Length = 2

class_2
Fons       25
Trànsit    14
Name: count, dtype: int64


============================================================
Column: 'contaminant_code'

Data = [8, 14, 7, 12, 10, 1, 6]
Length = 7

contaminant_code
8     7
7     7
12    7
14    5
10    5
1     4
6     4
Name: count, dtype: int64


============================================================

In [11]:
stn.print_individual_col(df_2019, 'longitude')
stn.print_individual_col(df_2019, 'latitude')

Column: 'longitude'

Data = [2.1874, 2.1538, 2.1534, 2.1151, 2.2045, 2.1331, 2.148]
Length = 7

2.1538    7
2.1534    7
2.1151    7
2.1480    7
2.1874    4
2.2045    4
2.1331    3
Name: longitude, dtype: int64


Column: 'latitude'

Data = [41.3864, 41.3853, 41.3987, 41.3875, 41.4039, 41.3788, 41.4261]
Length = 7

41.3853    7
41.3987    7
41.3875    7
41.4261    7
41.3864    4
41.4039    4
41.3788    3
Name: latitude, dtype: int64

In [11]:
stn.contaminants_df

    code                            desc  units
0      1                             SO2  µg/m³
6      6                              CO  mg/m³
1      7                              NO  µg/m³
2      8                             NO2  µg/m³
3      9                           PM2.5  µg/m³
7     10                            PM10  µg/m³
4     12                             NOx  µg/m³
5     14                              O3  µg/m³
8     22                    Black Carbon  µg/m³
12   996   Flow 2 (Mesura interna equip)    NaN
11   997   Flow 1 (Mesura interna equip)    NaN
10   998  Flow C (Mesura interna equip)
9    999           Biomassa Black Carbon      %

In [12]:
d_cond_2019, df_cond_2019 = stn.condense_stations_data(df_2019, stn.contaminants_df)

In [14]:
df_cond_2019

,station,station_name,code_dtes,zqa,code_eoi,longitude,latitude,location,district_code,district_name,neighborhood_code,neighborhood_name,class_1,class_2,contaminant_code,contaminant_names
0,4,Barcelona - Poblenou,I2,1,8019004,2.2045,41.4039,Plaça Josep Trueta (Pujades - Lope de Vega),10,Sant Marti,68,el Poblenou,Urbana,Fons,"[8, 10, 7, 12]","[NO2, PM10, NO, NOx]"
1,42,Barcelona - Sants,ID,1,8019042,2.1331,41.3788,Jardins de Can Mantega (Joan Güell - Violant d...,3,Sants-Montjuic,18,Sants,Urbana,Fons,"[8, 7, 12]","[NO2, NO, NOx]"
2,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.3853,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,"[8, 14, 10, 1, 6, 7, 12]","[NO2, O3, PM10, SO2, CO, NO, NOx]"
3,44,Barcelona - Gràcia,IJ,1,8019044,2.1534,41.3987,Plaça Gal·la Placídia (Via Augusta - Travesser...,6,Gracia,31,la Vila de Gracia,Urbana,Trànsit,"[8, 14, 10, 1, 6, 7, 12]","[NO2, O3, PM10, SO2, CO, NO, NOx]"
4,50,Barcelona - Ciutadella,IL,1,8019050,2.1874,41.3864,Parc de la Ciutadella,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Urbana,Fons,"[8, 14, 7, 12]","[NO2, O3, NO, NOx]"
5,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.4261,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,"[8, 14, 10, 1, 6, 12, 7]","[NO2, O3, PM10, SO2, CO, NOx, NO]"
6,57,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.3875,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,"[8, 14, 10, 1, 6, 7, 12]","[NO2, O3, PM10, SO2, CO, NO, NOx]"

In [78]:
data_2019 = {}

In [79]:
for index, row in df_cond_2019.iterrows():
    cols = list(df_cond_2019.columns)[1:]
    data_2019[row['station']] = {str(x): row[x] for x in cols}

In [85]:
#list(df_cond_2019.columns)[1:]
important_cols = [
    ('station_name', 'Station Name'),
    ('location', 'Location'),
    ('district_code', 'District Code'),
    ('district_name', 'District Name'),
    ('neighborhood_code', 'Neighborhood Code'),
    ('neighborhood_name', 'Neighborhood Name'),
    ('class_1', 'Station Class'),
    ('class_2', 'Station Sub-Class'),
    ('longitude', 'Longitude'),
    ('latitude', 'Latitude'),
    ('contaminant_code', 'Contaminants Codes'),
    ('contaminant_names', 'Contaminants Names')]

In [86]:
map_2019 = folium.Map(
    location = [df_cond_2019.latitude.mean(), df_cond_2019.longitude.mean()], 
    tiles = "OpenStreetMap", 
    zoom_start = 12
)

In [103]:
for k in data_2019.keys():
    msg = '<div style="min-width: 400px;" ><b>Station Id: ' + str(k) + '</b></br>'
    msg += '<ul>'
    for x in important_cols:
        msg += '<li><b><i>' + str(x[1]) + '</i></b> -- "' + str(data_2019[k][x[0]]) + '"'
    msg += '</ul></div>'

    #print(msg)
    
    folium.Marker(
      location = [data_2019[k]['latitude'], data_2019[k]['longitude']],
      #popup = [data_2019[k]['station_name'], data_2019[k]['latitude'], data_2019[k]['longitude']],
      popup = msg,
   ).add_to(map_2019)

In [104]:
map_2019

In [110]:
map_2019.save('.\interative_maps\map_2019.html')

## Stations in the year 2021

In [120]:
df_2021

,station,station_name,code_dtes,zqa,code_eoi,longitude,latitude,location,district_code,district_name,neighborhood_code,neighborhood_name,class_1,class_2,contaminant_code
0,50,Barcelona - Ciutadella,IL,1,8019050,2.1874,41.3864,Parc de la Ciutadella,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Urbana,Fons,8
1,50,Barcelona - Ciutadella,IL,1,8019050,2.1874,41.3864,Parc de la Ciutadella,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Urbana,Fons,14
2,50,Barcelona - Ciutadella,IL,1,8019050,2.1874,41.3864,Parc de la Ciutadella,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Urbana,Fons,7
3,50,Barcelona - Ciutadella,IL,1,8019050,2.1874,41.3864,Parc de la Ciutadella,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Urbana,Fons,12
4,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.3853,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,8
5,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.3853,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,14
6,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.3853,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,10
7,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.3853,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,1
8,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.3853,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,6
9,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.3853,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,7
10,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.3853,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,12
11,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.3853,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,22
12,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.3853,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,99
13,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.3853,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,996
14,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.3853,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,997
15,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.3853,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,998
16,44,Barcelona - Gràcia,IJ,1,8019044,2.1534,41.3987,Plaça Gal·la Placídia (Via Augusta - Travesser...,6,Gracia,31,la Vila de Gracia,Urbana,Trànsit,8
17,44,Barcelona - Gràcia,IJ,1,8019044,2.1534,41.3987,Plaça Gal·la Placídia (Via Augusta - Travesser...,6,Gracia,31,la Vila de Gracia,Urbana,Trànsit,14
18,44,Barcelona - Gràcia,IJ,1,8019044,2.1534,41.3987,Plaça Gal·la Placídia (Via Augusta - Travesser...,6,Gracia,31,la Vila de Gracia,Urbana,Trànsit,10
19,44,Barcelona - Gràcia,IJ,1,8019044,2.1534,41.3987,Plaça Gal·la Placídia (Via Augusta - Travesser...,6,Gracia,31,la Vila de Gracia,Urbana,Trànsit,1
20,44,Barcelona - Gràcia,IJ,1,8019044,2.1534,41.3987,Plaça Gal·la Placídia (Via Augusta - Travesser...,6,Gracia,31,la Vila de Gracia,Urbana,Trànsit,6
21,44,Barcelona - Gràcia,IJ,1,8019044,2.1534,41.3987,Plaça Gal·la Placídia (Via Augusta - Travesser...,6,Gracia,31,la Vila de Gracia,Urbana,Trànsit,7
22,44,Barcelona - Gràcia,IJ,1,8019044,2.1534,41.3987,Plaça Gal·la Placídia (Via Augusta - Travesser...,6,Gracia,31,la Vila de Gracia,Urbana,Trànsit,12
23,57,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.3875,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,8
24,57,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.3875,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,14
25,57,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.3875,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,10
26,57,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.3875,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,1
27,57,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.3875,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,6
28,57,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.3875,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,7
29,57,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.3875,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,9
30,57,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.3875,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,12
31,4,Barcelona - Poblenou,I2,1,8019004,2.2045,41.4039,Plaça Josep Trueta (Pujades - Lope de Vega),10,Sant Marti,68,el Poblenou,Urbana,Fons,8
32,4,Barcelona - Poblenou,I2,1,8019004,2.2045,41.4039,Plaça Josep Trueta (Pujades - Lope de Vega),10,Sant Marti,68,el Poblenou,Urbana,Fons,10
33,4,Barcelona - Poblenou,I2,1,8019004,2.2045,41.4039,Plaça Josep Trueta (Pujades - Lope de Vega),10,Sant Marti,68,el Poblenou,Urbana,Fons,7
34,4,Barcelona - Poblenou,I2,1,8019004,2.2045,41.4039,Plaça Josep Trueta (Pujades - Lope de Vega),10,Sant Marti,68,el Poblenou,Urbana,Fons,12
35,42,Barcelona - Sants,ID,1,8019042,2.1331,41.3788,Jardins de Can Mantega (Joan Güell - Violant d...,3,Sants-Montjuic,18,Sants,Urbana,Fons,8
36,42,Barcelona - Sants,ID,1,8019042,2.1331,41.3788,Jardins de Can Mantega (Joan Güell - Violant d...,3,Sants-Montjuic,18,Sants,Urbana,Fons,7
37,42,Barcelona - Sants,ID,1,8019042,2.1331,41.3788,Jardins de Can Mantega (Joan Güell - Violant d...,3,Sants-Montjuic,18,Sants,Urbana,Fons,12
38,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.4261,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,8
39,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.4261,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,14
40,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.4261,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,10
41,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.4261,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,1
42,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.4261,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,6
43,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.4261,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,12
44,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.4261,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,7
45,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.4261,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,22
46,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.4261,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,996
47,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.4261,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,997
48,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.4261,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,998
49,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.4261,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,999

In [121]:
df_2021.shape

(50, 15)

In [122]:
stn.print_categorical_cols(df_2021, eda_cols)

Column: 'station'

Data = [50, 43, 44, 57, 4, 42, 54]
Length = 7

station
43    12
54    12
57     8
44     7
50     4
4      4
42     3
Name: count, dtype: int64


============================================================
Column: 'station_name'

Data = ['Barcelona - Ciutadella', 'Barcelona - Eixample', 'Barcelona - Gràcia', 'Barcelona - Palau Reial', 'Barcelona - Poblenou', 'Barcelona - Sants', 'Barcelona - Vall Hebron']
Length = 7

station_name
Barcelona - Eixample       12
Barcelona - Vall Hebron    12
Barcelona - Palau Reial     8
Barcelona - Gràcia          7
Barcelona - Ciutadella      4
Barcelona - Poblenou        4
Barcelona - Sants           3
Name: count, dtype: int64


============================================================
Column: 'code_dtes'

Data = ['IL', 'IH', 'IJ', 'IZ', 'I2', 'ID', 'IN']
Length = 7

code_dtes
IH    12
IN    12
IZ     8
IJ     7
IL     4
I2     4
ID     3
Name: count, dtype: int64


============================================================
Column: 'zqa'

Data = [1]
Length = 1

zqa
1    50
Name: count, dtype: int64


============================================================
Column: 'code_eoi'

Data = [8019050, 8019043, 8019044, 8019057, 8019004, 8019042, 8019054]
Length = 7

code_eoi
8019043    12
8019054    12
8019057     8
8019044     7
8019050     4
8019004     4
8019042     3
Name: count, dtype: int64


============================================================
Column: 'location'

Data = ['Parc de la Ciutadella', 'Av. Roma - c/ Comte Urgell', 'Plaça Gal·la Placídia (Via Augusta - Travessera de Gràcia)', 'c/ John Maynard Keynes - c/ de Jordi Girona', 'Plaça Josep Trueta (Pujades - Lope de Vega)', 'Jardins de Can Mantega (Joan Güell - Violant d’Hongria)', 'Parc de la Vall d’Hebron. c/ Martí Codolar - c/ Granja Vella']
Length = 7

location
Av. Roma - c/ Comte Urgell                                      12
Parc de la Vall d’Hebron. c/ Martí Codolar - c/ Granja Vella    12
c/ John Maynard Keynes - c/ de Jordi Girona                      8
Plaça Gal·la Placídia (Via Augusta - Travessera de Gràcia)       7
Parc de la Ciutadella                                            4
Plaça Josep Trueta (Pujades - Lope de Vega)                      4
Jardins de Can Mantega (Joan Güell - Violant d’Hongria)          3
Name: count, dtype: int64


============================================================
Column: 'district_code'

Data = [1, 5, 6, 4, 10, 3, 7]
Length = 7

district_code
5     12
7     12
4      8
6      7
1      4
10     4
3      3
Name: count, dtype: int64


============================================================
Column: 'district_name'

Data = ['Ciutat Vella', 'Eixample', 'Gracia', 'Les Corts', 'Sant Marti', 'Sants-Montjuic', 'Horta-Guinardo']
Length = 7

district_name
Eixample          12
Horta-Guinardo    12
Les Corts          8
Gracia             7
Ciutat Vella       4
Sant Marti         4
Sants-Montjuic     3
Name: count, dtype: int64


============================================================
Column: 'neighborhood_code'

Data = [4, 9, 31, 21, 68, 18, 41]
Length = 7

neighborhood_code
9     12
41    12
21     8
31     7
4      4
68     4
18     3
Name: count, dtype: int64


============================================================
Column: 'neighborhood_name'

Data = ['Sant Pere, Santa Caterina i la Ribera', "la Nova Esquerra de l'Eixample", 'la Vila de Gracia', 'Pedralbes', 'el Poblenou', 'Sants', "la Vall d'Hebron"]
Length = 7

neighborhood_name
la Nova Esquerra de l'Eixample           12
la Vall d'Hebron                         12
Pedralbes                                 8
la Vila de Gracia                         7
Sant Pere, Santa Caterina i la Ribera     4
el Poblenou                               4
Sants                                     3
Name: count, dtype: int64


============================================================
Column: 'class_1'

Data = ['Urbana']
Length = 1

class_1
Urbana    50
Name: count, dtype: int64


============================================================
Column: 'class_2'

Data = ['Fons', 'Trànsit']
Length = 2

class_2
Fons       31
Trànsit    19
Name: count, dtype: int64


============================================================
Column: 'contaminant_code'

Data = [8, 14, 7, 12, 10, 1, 6, 22, 99, 996, 997, 998, 9, 999]
Length = 14

contaminant_code
8      7
7      7
12     7
14     5
10     5
1      4
6      4
22     2
996    2
997    2
998    2
99     1
9      1
999    1
Name: count, dtype: int64


============================================================

In [123]:
stn.print_individual_col(df_2021, 'longitude')
stn.print_individual_col(df_2021, 'latitude')

Column: 'longitude'

Data = [2.1874, 2.1538, 2.1534, 2.1151, 2.2045, 2.1331, 2.148]
Length = 7

longitude
2.1538    12
2.1480    12
2.1151     8
2.1534     7
2.1874     4
2.2045     4
2.1331     3
Name: count, dtype: int64


Column: 'latitude'

Data = [41.3864, 41.3853, 41.3987, 41.3875, 41.4039, 41.3788, 41.4261]
Length = 7

latitude
41.3853    12
41.4261    12
41.3875     8
41.3987     7
41.3864     4
41.4039     4
41.3788     3
Name: count, dtype: int64

In [124]:
stn.contaminants_df

    code                            desc  units
0      1                             SO2  µg/m³
6      6                              CO  mg/m³
1      7                              NO  µg/m³
2      8                             NO2  µg/m³
3      9                           PM2.5  µg/m³
7     10                            PM10  µg/m³
4     12                             NOx  µg/m³
5     14                              O3  µg/m³
8     22                    Black Carbon  µg/m³
12   996   Flow 2 (Mesura interna equip)    NaN
11   997   Flow 1 (Mesura interna equip)    NaN
10   998  Flow C (Mesura interna equip)
9    999           Biomassa Black Carbon      %

In [125]:
d_cond_2021, df_cond_2021 = stn.condense_stations_data(df_2021, stn.contaminants_df)

In [126]:
df_cond_2021

,station,station_name,code_dtes,zqa,code_eoi,longitude,latitude,location,district_code,district_name,neighborhood_code,neighborhood_name,class_1,class_2,contaminant_code,contaminant_names
0,4,Barcelona - Poblenou,I2,1,8019004,2.2045,41.4039,Plaça Josep Trueta (Pujades - Lope de Vega),10,Sant Marti,68,el Poblenou,Urbana,Fons,"[8, 10, 7, 12]","[NO2, PM10, NO, NOx]"
1,42,Barcelona - Sants,ID,1,8019042,2.1331,41.3788,Jardins de Can Mantega (Joan Güell - Violant d...,3,Sants-Montjuic,18,Sants,Urbana,Fons,"[8, 7, 12]","[NO2, NO, NOx]"
2,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.3853,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,"[8, 14, 10, 1, 6, 7, 12, 22, 99, 996, 997, 998]","[NO2, O3, PM10, SO2, CO, NO, NOx, Black Carbon..."
3,44,Barcelona - Gràcia,IJ,1,8019044,2.1534,41.3987,Plaça Gal·la Placídia (Via Augusta - Travesser...,6,Gracia,31,la Vila de Gracia,Urbana,Trànsit,"[8, 14, 10, 1, 6, 7, 12]","[NO2, O3, PM10, SO2, CO, NO, NOx]"
4,50,Barcelona - Ciutadella,IL,1,8019050,2.1874,41.3864,Parc de la Ciutadella,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Urbana,Fons,"[8, 14, 7, 12]","[NO2, O3, NO, NOx]"
5,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.4261,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,"[8, 14, 10, 1, 6, 12, 7, 22, 996, 997, 998, 999]","[NO2, O3, PM10, SO2, CO, NOx, NO, Black Carbon..."
6,57,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.3875,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,"[8, 14, 10, 1, 6, 7, 9, 12]","[NO2, O3, PM10, SO2, CO, NO, PM2.5, NOx]"

In [127]:
data_2021 = {}

In [129]:
for index, row in df_cond_2021.iterrows():
    cols = list(df_cond_2021.columns)[1:]
    data_2021[row['station']] = {str(x): row[x] for x in cols}

In [130]:
map_2021 = folium.Map(
    location = [df_cond_2021.latitude.mean(), df_cond_2021.longitude.mean()], 
    tiles = "OpenStreetMap", 
    zoom_start = 12
)

In [131]:
for k in data_2021.keys():
    msg = '<div style="min-width: 400px;" ><b>Station Id: ' + str(k) + '</b></br>'
    msg += '<ul>'
    for x in important_cols:
        msg += '<li><b><i>' + str(x[1]) + '</i></b> -- "' + str(data_2021[k][x[0]]) + '"'
    msg += '</ul></div>'

    #print(msg)
    
    folium.Marker(
      location = [data_2021[k]['latitude'], data_2021[k]['longitude']],
      #popup = [data_2019[k]['station_name'], data_2019[k]['latitude'], data_2019[k]['longitude']],
      popup = msg,
   ).add_to(map_2021)

In [132]:
map_2021

In [133]:
map_2021.save('.\interative_maps\map_2021.html')

## Stations in the year 2022

In [140]:
df_2022

,station,station_name,code_dtes,zqa,code_eoi,longitude,latitude,location,district_code,district_name,neighborhood_code,neighborhood_name,class_1,class_2,contaminant_code
0,50,Barcelona - Ciutadella,IL,1,8019050,2.1874,41.38640,Parc de la Ciutadella,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Urbana,Fons,8
1,50,Barcelona - Ciutadella,IL,1,8019050,2.1874,41.38640,Parc de la Ciutadella,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Urbana,Fons,14
2,50,Barcelona - Ciutadella,IL,1,8019050,2.1874,41.38640,Parc de la Ciutadella,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Urbana,Fons,7
3,50,Barcelona - Ciutadella,IL,1,8019050,2.1874,41.38640,Parc de la Ciutadella,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Urbana,Fons,12
4,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.38530,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,8
5,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.38530,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,14
6,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.38530,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,10
7,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.38530,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,1
8,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.38530,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,6
9,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.38530,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,7
10,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.38530,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,12
11,44,Barcelona - Gràcia,IJ,1,8019044,2.1534,41.39870,Plaça Gal·la Placídia (Via Augusta - Travesser...,6,Gracia,31,la Vila de Gracia,Urbana,Trànsit,8
12,44,Barcelona - Gràcia,IJ,1,8019044,2.1534,41.39870,Plaça Gal·la Placídia (Via Augusta - Travesser...,6,Gracia,31,la Vila de Gracia,Urbana,Trànsit,14
13,44,Barcelona - Gràcia,IJ,1,8019044,2.1534,41.39870,Plaça Gal·la Placídia (Via Augusta - Travesser...,6,Gracia,31,la Vila de Gracia,Urbana,Trànsit,10
14,44,Barcelona - Gràcia,IJ,1,8019044,2.1534,41.39870,Plaça Gal·la Placídia (Via Augusta - Travesser...,6,Gracia,31,la Vila de Gracia,Urbana,Trànsit,1
15,44,Barcelona - Gràcia,IJ,1,8019044,2.1534,41.39870,Plaça Gal·la Placídia (Via Augusta - Travesser...,6,Gracia,31,la Vila de Gracia,Urbana,Trànsit,6
16,44,Barcelona - Gràcia,IJ,1,8019044,2.1534,41.39870,Plaça Gal·la Placídia (Via Augusta - Travesser...,6,Gracia,31,la Vila de Gracia,Urbana,Trànsit,7
17,44,Barcelona - Gràcia,IJ,1,8019044,2.1534,41.39870,Plaça Gal·la Placídia (Via Augusta - Travesser...,6,Gracia,31,la Vila de Gracia,Urbana,Trànsit,12
18,57,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.38750,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,8
19,57,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.38750,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,14
20,57,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.38750,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,10
21,57,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.38750,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,1
22,57,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.38750,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,6
23,57,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.38750,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,7
24,57,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.38750,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,12
25,4,Barcelona - Poblenou,I2,1,8019004,2.2045,41.40390,Plaça Josep Trueta (Pujades - Lope de Vega),10,Sant Marti,68,el Poblenou,Urbana,Fons,8
26,4,Barcelona - Poblenou,I2,1,8019004,2.2045,41.40390,Plaça Josep Trueta (Pujades - Lope de Vega),10,Sant Marti,68,el Poblenou,Urbana,Fons,10
27,4,Barcelona - Poblenou,I2,1,8019004,2.2045,41.40390,Plaça Josep Trueta (Pujades - Lope de Vega),10,Sant Marti,68,el Poblenou,Urbana,Fons,7
28,4,Barcelona - Poblenou,I2,1,8019004,2.2045,41.40390,Plaça Josep Trueta (Pujades - Lope de Vega),10,Sant Marti,68,el Poblenou,Urbana,Fons,12
29,42,Barcelona - Sants,ID,1,8019042,2.1331,41.37880,Jardins de Can Mantega (Joan Güell - Violant d...,3,Sants-Montjuic,18,Sants,Urbana,Fons,8
30,42,Barcelona - Sants,ID,1,8019042,2.1331,41.37880,Jardins de Can Mantega (Joan Güell - Violant d...,3,Sants-Montjuic,18,Sants,Urbana,Fons,7
31,42,Barcelona - Sants,ID,1,8019042,2.1331,41.37880,Jardins de Can Mantega (Joan Güell - Violant d...,3,Sants-Montjuic,18,Sants,Urbana,Fons,12
32,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.42610,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,8
33,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.42610,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,14
34,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.42610,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,10
35,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.42610,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,1
36,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.42610,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,6
37,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.42610,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,12
38,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.42610,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,7
39,58,Barcelona - Observatori Fabra,IZ,1,8019058,2.1239,41.41843,Camí de l'Observatori-s/n,5,Sarria-Sant Gervasi,22,Vallvidrera-el Tibidabo-les Planes,Suburbana,Fons,8
40,58,Barcelona - Observatori Fabra,IZ,1,8019058,2.1239,41.41843,Camí de l'Observatori-s/n,5,Sarria-Sant Gervasi,22,Vallvidrera-el Tibidabo-les Planes,Suburbana,Fons,14
41,58,Barcelona - Observatori Fabra,IZ,1,8019058,2.1239,41.41843,Camí de l'Observatori-s/n,5,Sarria-Sant Gervasi,22,Vallvidrera-el Tibidabo-les Planes,Suburbana,Fons,10
42,58,Barcelona - Observatori Fabra,IZ,1,8019058,2.1239,41.41843,Camí de l'Observatori-s/n,5,Sarria-Sant Gervasi,22,Vallvidrera-el Tibidabo-les Planes,Suburbana,Fons,7
43,58,Barcelona - Observatori Fabra,IZ,1,8019058,2.1239,41.41843,Camí de l'Observatori-s/n,5,Sarria-Sant Gervasi,22,Vallvidrera-el Tibidabo-les Planes,Suburbana,Fons,12

In [141]:
df_2022.shape

(44, 15)

In [142]:
stn.print_categorical_cols(df_2022, eda_cols)

Column: 'station'

Data = [50, 43, 44, 57, 4, 42, 54, 58]
Length = 8

station
43    7
44    7
57    7
54    7
58    5
50    4
4     4
42    3
Name: count, dtype: int64


============================================================
Column: 'station_name'

Data = ['Barcelona - Ciutadella', 'Barcelona - Eixample', 'Barcelona - Gràcia', 'Barcelona - Palau Reial', 'Barcelona - Poblenou', 'Barcelona - Sants', 'Barcelona - Vall Hebron', 'Barcelona - Observatori Fabra']
Length = 8

station_name
Barcelona - Eixample             7
Barcelona - Gràcia               7
Barcelona - Palau Reial          7
Barcelona - Vall Hebron          7
Barcelona - Observatori Fabra    5
Barcelona - Ciutadella           4
Barcelona - Poblenou             4
Barcelona - Sants                3
Name: count, dtype: int64


============================================================
Column: 'code_dtes'

Data = ['IL', 'IH', 'IJ', 'IZ', 'I2', 'ID', 'IN']
Length = 7

code_dtes
IZ    12
IH     7
IJ     7
IN     7
IL     4
I2     4
ID     3
Name: count, dtype: int64


============================================================
Column: 'zqa'

Data = [1]
Length = 1

zqa
1    44
Name: count, dtype: int64


============================================================
Column: 'code_eoi'

Data = [8019050, 8019043, 8019044, 8019057, 8019004, 8019042, 8019054, 8019058]
Length = 8

code_eoi
8019043    7
8019044    7
8019057    7
8019054    7
8019058    5
8019050    4
8019004    4
8019042    3
Name: count, dtype: int64


============================================================
Column: 'location'

Data = ['Parc de la Ciutadella', 'Av. Roma - c/ Comte Urgell', 'Plaça Gal·la Placídia (Via Augusta - Travessera de Gràcia)', 'c/ John Maynard Keynes - c/ de Jordi Girona', 'Plaça Josep Trueta (Pujades - Lope de Vega)', 'Jardins de Can Mantega (Joan Güell - Violant d’Hongria)', 'Parc de la Vall d’Hebron. c/ Martí Codolar - c/ Granja Vella', "Camí de l'Observatori-s/n"]
Length = 8

location
Av. Roma - c/ Comte Urgell                                      7
Plaça Gal·la Placídia (Via Augusta - Travessera de Gràcia)      7
c/ John Maynard Keynes - c/ de Jordi Girona                     7
Parc de la Vall d’Hebron. c/ Martí Codolar - c/ Granja Vella    7
Camí de l'Observatori-s/n                                       5
Parc de la Ciutadella                                           4
Plaça Josep Trueta (Pujades - Lope de Vega)                     4
Jardins de Can Mantega (Joan Güell - Violant d’Hongria)         3
Name: count, dtype: int64


============================================================
Column: 'district_code'

Data = [1, 5, 6, 4, 10, 3, 7]
Length = 7

district_code
5     12
6      7
4      7
7      7
1      4
10     4
3      3
Name: count, dtype: int64


============================================================
Column: 'district_name'

Data = ['Ciutat Vella', 'Eixample', 'Gracia', 'Les Corts', 'Sant Marti', 'Sants-Montjuic', 'Horta-Guinardo', 'Sarria-Sant Gervasi']
Length = 8

district_name
Eixample               7
Gracia                 7
Les Corts              7
Horta-Guinardo         7
Sarria-Sant Gervasi    5
Ciutat Vella           4
Sant Marti             4
Sants-Montjuic         3
Name: count, dtype: int64


============================================================
Column: 'neighborhood_code'

Data = [4, 9, 31, 21, 68, 18, 41, 22]
Length = 8

neighborhood_code
9     7
31    7
21    7
41    7
22    5
4     4
68    4
18    3
Name: count, dtype: int64


============================================================
Column: 'neighborhood_name'

Data = ['Sant Pere, Santa Caterina i la Ribera', "la Nova Esquerra de l'Eixample", 'la Vila de Gracia', 'Pedralbes', 'el Poblenou', 'Sants', "la Vall d'Hebron", 'Vallvidrera-el Tibidabo-les Planes']
Length = 8

neighborhood_name
la Nova Esquerra de l'Eixample           7
la Vila de Gracia                        7
Pedralbes                                7
la Vall d'Hebron                         7
Vallvidrera-el Tibidabo-les Planes       5
Sant Pere, Santa Caterina i la Ribera    4
el Poblenou                              4
Sants                                    3
Name: count, dtype: int64


============================================================
Column: 'class_1'

Data = ['Urbana', 'Suburbana']
Length = 2

class_1
Urbana       39
Suburbana     5
Name: count, dtype: int64


============================================================
Column: 'class_2'

Data = ['Fons', 'Trànsit']
Length = 2

class_2
Fons       30
Trànsit    14
Name: count, dtype: int64


============================================================
Column: 'contaminant_code'

Data = [8, 14, 7, 12, 10, 1, 6]
Length = 7

contaminant_code
8     8
7     8
12    8
14    6
10    6
1     4
6     4
Name: count, dtype: int64


============================================================

In [143]:
stn.print_individual_col(df_2022, 'longitude')
stn.print_individual_col(df_2022, 'latitude')

Column: 'longitude'

Data = [2.1874, 2.1538, 2.1534, 2.1151, 2.2045, 2.1331, 2.148, 2.1239]
Length = 8

longitude
2.1538    7
2.1534    7
2.1151    7
2.1480    7
2.1239    5
2.1874    4
2.2045    4
2.1331    3
Name: count, dtype: int64


Column: 'latitude'

Data = [41.3864, 41.3853, 41.3987, 41.3875, 41.4039, 41.3788, 41.4261, 41.41843]
Length = 8

latitude
41.38530    7
41.39870    7
41.38750    7
41.42610    7
41.41843    5
41.38640    4
41.40390    4
41.37880    3
Name: count, dtype: int64

In [144]:
d_cond_2022, df_cond_2022 = stn.condense_stations_data(df_2022, stn.contaminants_df)

In [145]:
df_cond_2022

,station,station_name,code_dtes,zqa,code_eoi,longitude,latitude,location,district_code,district_name,neighborhood_code,neighborhood_name,class_1,class_2,contaminant_code,contaminant_names
0,4,Barcelona - Poblenou,I2,1,8019004,2.2045,41.40390,Plaça Josep Trueta (Pujades - Lope de Vega),10,Sant Marti,68,el Poblenou,Urbana,Fons,"[8, 10, 7, 12]","[NO2, PM10, NO, NOx]"
1,42,Barcelona - Sants,ID,1,8019042,2.1331,41.37880,Jardins de Can Mantega (Joan Güell - Violant d...,3,Sants-Montjuic,18,Sants,Urbana,Fons,"[8, 7, 12]","[NO2, NO, NOx]"
2,43,Barcelona - Eixample,IH,1,8019043,2.1538,41.38530,Av. Roma - c/ Comte Urgell,5,Eixample,9,la Nova Esquerra de l'Eixample,Urbana,Trànsit,"[8, 14, 10, 1, 6, 7, 12]","[NO2, O3, PM10, SO2, CO, NO, NOx]"
3,44,Barcelona - Gràcia,IJ,1,8019044,2.1534,41.39870,Plaça Gal·la Placídia (Via Augusta - Travesser...,6,Gracia,31,la Vila de Gracia,Urbana,Trànsit,"[8, 14, 10, 1, 6, 7, 12]","[NO2, O3, PM10, SO2, CO, NO, NOx]"
4,50,Barcelona - Ciutadella,IL,1,8019050,2.1874,41.38640,Parc de la Ciutadella,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Urbana,Fons,"[8, 14, 7, 12]","[NO2, O3, NO, NOx]"
5,54,Barcelona - Vall Hebron,IN,1,8019054,2.1480,41.42610,Parc de la Vall d’Hebron. c/ Martí Codolar - c...,7,Horta-Guinardo,41,la Vall d'Hebron,Urbana,Fons,"[8, 14, 10, 1, 6, 12, 7]","[NO2, O3, PM10, SO2, CO, NOx, NO]"
6,57,Barcelona - Palau Reial,IZ,1,8019057,2.1151,41.38750,c/ John Maynard Keynes - c/ de Jordi Girona,4,Les Corts,21,Pedralbes,Urbana,Fons,"[8, 14, 10, 1, 6, 7, 12]","[NO2, O3, PM10, SO2, CO, NO, NOx]"
7,58,Barcelona - Observatori Fabra,IZ,1,8019058,2.1239,41.41843,Camí de l'Observatori-s/n,5,Sarria-Sant Gervasi,22,Vallvidrera-el Tibidabo-les Planes,Suburbana,Fons,"[8, 14, 10, 7, 12]","[NO2, O3, PM10, NO, NOx]"

In [146]:
data_2022 = {}

In [147]:
for index, row in df_cond_2022.iterrows():
    cols = list(df_cond_2022.columns)[1:]
    data_2022[row['station']] = {str(x): row[x] for x in cols}

In [148]:
map_2022 = folium.Map(
    location = [df_cond_2022.latitude.mean(), df_cond_2022.longitude.mean()], 
    tiles = "OpenStreetMap", 
    zoom_start = 12
)

In [149]:
for k in data_2022.keys():
    msg = '<div style="min-width: 400px;" ><b>Station Id: ' + str(k) + '</b></br>'
    msg += '<ul>'
    for x in important_cols:
        msg += '<li><b><i>' + str(x[1]) + '</i></b> -- "' + str(data_2022[k][x[0]]) + '"'
    msg += '</ul></div>'

    #print(msg)
    
    folium.Marker(
      location = [data_2022[k]['latitude'], data_2022[k]['longitude']],
      #popup = [data_2019[k]['station_name'], data_2019[k]['latitude'], data_2019[k]['longitude']],
      popup = msg,
   ).add_to(map_2022)

In [150]:
map_2022

In [151]:
map_2022.save('.\interative_maps\map_2022.html')

In [164]:
import json
#from numpyencoder import NumpyEncoder

ModuleNotFoundError: No module named 'numpyencoder'

In [171]:
#type(data_2019[4]['contaminant_names'])
data_2019[4]

{'station_name': 'Barcelona - Poblenou',
 'code_dtes': 'I2',
 'zqa': 1,
 'code_eoi': 8019004,
 'longitude': 2.2045,
 'latitude': 41.4039,
 'location': 'Plaça Josep Trueta (Pujades - Lope de Vega)',
 'district_code': 10,
 'district_name': 'Sant Marti',
 'neighborhood_code': 68,
 'neighborhood_name': 'el Poblenou',
 'class_1': 'Urbana',
 'class_2': 'Fons',
 'contaminant_code': [8, 10, 7, 12],
 'contaminant_names': ['NO2', 'PM10', 'NO', 'NOx']}

In [160]:
data_dump = {
    '2019': {str(x) : data_2019[x] for x in data_2019},
    '2021': {str(x) : data_2021[x] for x in data_2021},
    '2022': {str(x) : data_2022[x] for x in data_2022},
}

In [161]:
json_object = json.dumps(data_dump, indent=4)

TypeError: Object of type int64 is not JSON serializable

In [ ]:
#criar graficos para todos os anos
# comparar stations de todos os anos (numero, e poluentes)
#ver quais sao os poluentes mais importantes para barcelona e apenas vamos trabalhar nesses (NO2, O3, PM10, NOx)